variable "customer" {}
variable "environment" {}
variable "aws_region" {}
variable "white_bastion_ips" {}
variable "keypair" {}
variable "elasticsearch_blue_asg_min" {}
variable "elasticsearch_blue_asg_max" {}
variable "elasticsearch_blue_asg_desired" {}
variable "elasticsearch_green_asg_min" {}
variable "elasticsearch_green_asg_max" {}
variable "elasticsearch_green_asg_desired" {}